name: Add reviewers for PRs
on: [pull_request]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          org:
            - 'org/**'
          tech:
            - 'tech/**'
            
    - uses: delivery-much/actions-assigner@v1
      if: steps.changes.outputs.org == 'true'
      with:
        token: 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
        team-reviewers: hazelcast/apis
        
    - uses: delivery-much/actions-assigner@v1
      if: steps.changes.outputs.tech == 'true'
      with:
        token: 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
        reviewers: yuce,sancar,zpqrtbnk,ihsandemir
